### ISSUE TITLE
please help with react hooks problem more instances of react.

### ISSUE THREAD

**Issue by kordeviant** [revelrylabs/elixir_react_render#25]
i have a fork of your repo with not much change other than babel plugins,
but i get error using hooks in my components , something related to two instances of react or something , using your library through phoenix. 
here is the fork : https://github.com/kordeviant/elixir_react_render
here is the repo and submodules : https://github.com/kordeviant/elixir-react-gigalixir
i would really appreciate it if you could try to clone the repo and take a look

**Comment by oohnoitz** [comment]
Previously, the version of `react` and `react-dom` bundled with the package was fairly old and didn't have support for the new `React Hooks`. This should be fixed in `3.0.0` since `react` and `react-dom` has been made a `peer-dependency` instead. This means that there won't be any odd version mismatches.
